### PR TITLE
Support EIP-155 in E2E test

### PR DESCRIPTION
**Pull request by nkuba**
We update dependencies to the latest versions to support EIP-155 replay-protected transactions.

`PrivateKeyWalletSubprovider` expects `chainId` to be provided as a constructor argument. If the value is not provided the provider assumes it deals with mainnet (`chainId = 1`).

After EIP-155 the `chainId` is included when calculating a signature, and transactions that are sent to the Ethereum endpoint with non-matching `chainId` are rejected with `invalid sender`.

The previous solution worked fine with Ethereum endpoint that had replay protection disabled, but once the protection is enabled we need to include the correct `chainId` in the transaction signature.

### CODE REVIEW

**Comment by nkuba** [comment]
I invoked a test run for this branch to see if the fix works: https://github.com/keep-network/local-setup/runs/3789133012

**Comment by michalinacienciala** [comment]
> I invoked a test run for this branch to see if the fix works: https://github.com/keep-network/local-setup/runs/3789133012

I see that the job has failed during installation of `keep-ecdsa`, which is strange, because your changes didn’t touch that area (and E2E tests on `main` are failing at later stage) :thinking_face:

**Comment by michalinacienciala** [comment]
> > I invoked a test run for this branch to see if the fix works: https://github.com/keep-network/local-setup/runs/3789133012
> 
> I see that the job has failed during installation of `keep-ecdsa`, which is strange, because your changes didn’t touch that area (and E2E tests on `main` are failing at later stage) :thinking_face:

@nkuba, it looks that the failure was not related to your changes - it was a result of migration random-beacon code from `solidity/` to `solidity-v1/` in `keep-core`. I [crated a PR that should fix it](https://github.com/keep-network/local-setup/pull/123), I'm testing it right now. Once I confirm, we can merge the changes to main, update your branch and run the tests here again.

**Comment by nkuba** [comment]
Next try: https://github.com/keep-network/local-setup/actions/runs/1434707961

**Comment by michalinacienciala** [comment]
> Next try: https://github.com/keep-network/local-setup/actions/runs/1434707961

Unfortunately it's still failing with this `web3 is not defined` issue...

**Comment by nkuba** [comment]
> > Next try: https://github.com/keep-network/local-setup/actions/runs/1434707961
> 
> Unfortunately it's still failing with this `web3 is not defined` issue...

Of course, it does fail. I forgot to commit the change 😅 I'm sorry, one more try! 🤞🏻 
https://github.com/keep-network/local-setup/actions/runs/1439292511

**Comment by michalinacienciala** [comment]
> Of course, it does fail. I forgot to commit the change 😅 I'm sorry, one more try! 🤞🏻 https://github.com/keep-network/local-setup/actions/runs/1439292511

This time we've got this:
```
Starting deposit number [1]...

Test errored out with error:  TypeError: Cannot read property 'toBN' of undefined
    at createDeposit (file:///home/runner/work/local-setup/local-setup/e2e/e2e-test.js:265:16)
```

**Comment by michalinacienciala** [comment]
@nkuba, what's the status of this PR? Any chance for getting the tests fixed?

**Review by michalinacienciala — APPROVED** [review]
After latest changes tests are passing (see https://github.com/keep-network/local-setup/actions/runs/1654085605). Approving.

**Pull request merged**
