### PR TITLE
Reflect Correct Node Version in manual-setup.adoc

### PR DESCRIPTION
**Pull request by beaushinkle**
redux of #64 so I could edit it a bit!

The suggested node version in the manual setup doc is behind what we actually use, so this brings the doc up to date.

Tagging @Shadowfiend for review. Inspired by @dougvk :heart:

### CODE REVIEW

**Review by Shadowfiend — APPROVED** [review]

**Comment by Shadowfiend** [comment]
Please amend the commit and add this line to the end of the commit message:

```
Co-Authored-By: dougvk <dougvk@gmail.com>
```

**Comment by Shadowfiend** [comment]
(I believe you could have achieved a similar effect by branching off of Doug's branch, then doing `git commit --amend` after your changes, or cherry-picking his commit to a clean branch and doing a `git commit --amend`.)

**Comment by beaushinkle** [comment]
boomtown

**Review by Shadowfiend — APPROVED** [review]
🎉

**Pull request merged**
